import Head from 'next/head'
import Image from 'next/image'

import Reuniao from '@/components/Home/Reuniao'
import ShortAbout from '@/components/Home/ShortAbout'




export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <ShortAbout />
                <Reuniao />
            </main> 
        </>
    )
}


